version: '3.8'

services:
  token-api:
    image: postgres
    env_file:
      - .env
    container_name: token-api
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - token-api-network
    restart: always

networks:
  token-api-network:
    driver: bridge
